sudo: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_install:
  - sudo add-apt-repository ppa:forkotov02/opt-qt-5.11.1-trusty -y
  - sudo apt-get update -q
  - sudo apt-get install qt511base qt511tools qt511translations qt511x11extras -y
  - sudo apt-get install build-essential libgl1-mesa-dev -y
  - /opt/qt511/bin/qt511-env.sh

script:
  - cd test
  - qmake -project
  - qmake unit_tests.pro
  - make
  - ./unit_tests
  - cd ..
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master