sudo: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_install:
  - wget https://download.qt.io/official_releases/qt/5.11/5.11.1/qt-opensource-linux-x64-5.11.1.run
  - chmod +x qt-opensource-linux-x64-5.11.1.run
  - sudo ./qt-opensource-linux-x64-5.11.1.run
  - sudo apt-get install build-essential libgl1-mesa-dev  

script:
  - cd test
  - qmake -project
  - qmake unit_tests.pro
  - ./unit_tests
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master